version: "3"

services:
  selene:
    build: .
    environment:
      - SELENE_DB_HOST=postgres
      - SELENE_DB_NAME=/run/secrets/pg_database
      - SELENE_DB_USER=/run/secrets/pg_user
      - SELENE_DB_PW=/run/secrets/pg_password
      - SELENE_SESSION_AUTH_KEY=/run/secrets/session_auth
      - SELENE_SESSION_CRYPTO_KEY=/run/secrets/session_crypto
      - SELENE_PW_PEPPER=/run/secrets/password_pepper
      - SELENE_CSRF_SECRET=/run/secrets/csrf
      - SELENE_SERVER_PORT=8080
    ports:
      - 8080:8080
    secrets:
      - pg_database
      - pg_user
      - pg_password
      - session_auth
      - session_crypto
      - password_pepper
      - csrf
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - selene-postgres-net
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_DB_FILE=/run/secrets/pg_database
      - POSTGRES_USER_FILE=/run/secrets/pg_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    ports:
      - 5432:5432
    secrets:
      - pg_database
      - pg_user
      - pg_password
    networks:
      - selene-postgres-net

secrets:
  pg_database:
    file: ./pg_database.scrt
  pg_user:
    file: ./pg_user.scrt
  pg_password:
    file: ./pg_password.scrt
  session_auth:
    file: ./session_auth.scrt
  session_crypto:
    file: ./session_crypto.scrt
  password_pepper:
    file: ./password_pepper.scrt
  csrf:
    file: ./csrf.scrt

networks:
  selene-postgres-net:
    driver: bridge
